# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

.before-script-common: &before-script-common
  - python -V  # Print out python version for debugging
  - pip install -r requirements-test.txt

test:
  stage: test
  image: "python:$PYTHON"
  before_script:
    - *before-script-common
    - pip install "django$DJANGO"
  parallel:
    matrix:
      - PYTHON: "3.8"
        DJANGO:
          - ">=3.2,<4.0"
          - ">=4.0,<4.1"
          - ">=4.1,<4.2"
      - PYTHON: "3.9"
        DJANGO:
          - ">=3.2,<4.0"
          - ">=4.0,<4.1"
          - ">=4.1,<4.2"
      - PYTHON: "3.10"
        DJANGO:
          - ">=3.2,<4.0"
          - ">=4.0,<4.1"
          - ">=4.1,<4.2"
  script:
    - coverage run --source=easys_ordermanager manage.py test
    - flake8 easys_ordermanager

publish:
  stage: deploy
  image: python:latest
  script:
    - pip install -U twine build
    - python -m build
    - twine upload dist/*
  # job is only run against the main branch
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: pypi
