# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

test:
  stage: test
  image: "python:$PYTHON"
  before_script:
    - python -V  # Print out python version for debugging
    - pip install -r requirements-test.txt
    - pip install "django$DJANGO"
    - pip install "djangorestframework$DRF"
  parallel:
    matrix:
      - PYTHON: "3.8"
        DJANGO:
          - ">=3.2,<4.0"
          - ">=4.0,<4.1"
          - ">=4.1,<4.2"
        DRF:
          - ">=3.11,<3.12"
          - ">=3.12,<3.13"
          - ">=3.13,<3.14"
      - PYTHON: "3.9"
        DJANGO:
          - ">=3.2,<4.0"
          - ">=4.0,<4.1"
          - ">=4.1,<4.2"
        DRF:
          - ">=3.11,<3.12"
          - ">=3.12,<3.13"
          - ">=3.13,<3.14"
      - PYTHON: "3.10"
        DJANGO:
          - ">=3.2,<4.0"
          - ">=4.0,<4.1"
          - ">=4.1,<4.2"
        DRF:
          - ">=3.11,<3.12"
          - ">=3.12,<3.13"
          - ">=3.13,<3.14"
  script:
    - coverage run --source=easys_ordermanager manage.py test
    - flake8 easys_ordermanager

publish:
  stage: deploy
  # job only runs for tags on main branch
  only:
    refs:
      - main
    variables:
      - $CI_COMMIT_TAG
  image: python:latest
  script:
    - pip install -U twine build
    - python -m build
    - twine upload dist/*
  environment: pypi
