dist: focal
os: linux
language: python

cache:
  pip: true

python:
  - "3.7"
  - "3.8"

env:
  - TOXENV=py-django22
  - TOXENV=py-django30

before_install:
  - pip install tox

script:
  - tox
  - flake8 easys_ordermanager

stages:
  - test
  - deploy

jobs:
  fast_finish: true
  include:
    - stage: deploy
      if: tag IS present
      script: skip
      after_success:
        - coveralls
      deploy:
        provider: pypi
        distributions: sdist
        username: RegioHelden
        password:
          secure: "QA9vKMNbg73RUc8K1FS+XEslT73jmMgH+pxDgwPvHyigZbchLYqtLr7tKqfLfJdiftb1F2g5qEVr/Thgr+jS2bueoY7lf/5FK/0+7L8IyFGpqBWge8It4ZGvbnhY/r3MyEtiwekwU19O/+egthIg55oHVvNCi6nmhKak32Qu3c/LYKTmfsn2neARaTRKlf5BWVEX9fgZ/zQFLAAS4eEhRunqsFqj0KhPp9J7nZyDPajfn2ri551820u6W82448WQnHOkNxhApC8f4VNVCJnSqEIShTczjr+tVIDXJj4FytIcHljbbRe/7Ik3IE3FN/T/1J2M+aF8spjn/SUr26Fd+kUDWY413ol1xFhf80ckyM5rna0Q9QXzdnn81Rvn7y6oexzORJKm5eYHQR3qXx343BHbnCXlpsLqwDVVByxkw6KUzBAzSI4TGlW/Sow1flxnPwC8Yq7RCwk2ecI6g1sXZRiyguXMUsM/NoP4RhrfmcNQX7+f0jG24kuKxkY8Mmy6oy12HWlY8rEPNrgQ7noeDMOgG8lfvcSLwtMKGebwzXlP9nfuiLuCNii8mCH+n8AjJhF1nYPgcDIpmXW4gfyAerpn4wHBOKgnQa6Op8W0LJ7ZqTTlqt7sw/46BXev6icj6ZCT9vJcZ3JKiwPugdkT7iA9bDzfYQZCqTj0pSTmAQY="
        on:
          tags: true
