version: '3.5'

services:
  django:
    build: .
    user: app
    command: test
    volumes:
      - .:/app:cached
    environment:
      SHELL: /bin/bash
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
    restart: unless-stopped
    networks:
      default:
        aliases:
          - ordermanager

networks:
  default:
    name: rh-dev.eu
    ipam:
      config:
        - subnet: 10.199.0.0/16
